server.port=${PORT:8081}

spring.application.name=myproject1

# PostgreSQL Database Configuration (Render)
spring.datasource.url=jdbc:postgresql://dpg-d6khud56ubrc73ege3l0-a.singapore-postgres.render.com:5432/demo_backend_iu4v
spring.datasource.username=demo_backend_iu4v_user
spring.datasource.password=svIerjVUpPfTQG8d23fQQXcPFp4ygGqq
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false